#!/usr/bin/env bash
# TermuxAgent installer — Termux (Android), Linux, macOS.
#
#   in Termux:   pkg install -y git python && git clone <repo> && cd TermuxAgent0 && bash install.sh
#   one-liner:   curl -fsSL https://raw.githubusercontent.com/sachintha82288-cpu/TermuxAgent0/main/install.sh | bash
#
# What it does:
#   1. makes sure python3 exists (pkg install python on Termux)
#   2. copies the app to ~/.termux-agent/app (safe to delete the repo after)
#   3. installs the `agent` and `Agent` commands into PATH
#   4. runs the setup wizard (provider · API key · model · theme)
set -e

GREEN='\033[32m'; YELLOW='\033[33m'; CYAN='\033[36m'; MAGENTA='\033[35m'; RESET='\033[0m'
say()  { printf "${GREEN}[+]${RESET} %s\n" "$1"; }
ask()  { printf "${CYAN}[?]${RESET} %s" "$1"; }
warn() { printf "${YELLOW}[!]${RESET} %s\n" "$1"; }
logo() { printf "${MAGENTA}"
         printf '  ████████ ██ ██████   ████  ██   ██ ███    ██ ███████ ██████ \n'
         printf '  ─── TermuxAgent ── the AI that lives in your terminal ───\n'
         printf "${RESET}\n"; }

AUTO=0
case "${1:-}" in --auto|-y) AUTO=1 ;; esac

REPO_URL="https://github.com/sachintha82288-cpu/TermuxAgent0.git"

# When piped (curl … | bash) stdin is the script itself, so read answers
# from the terminal instead; if there is no terminal, go non-interactive.
if [ -t 0 ]; then
    IN=/dev/stdin
elif [ -r /dev/tty ] && ( : </dev/tty ) 2>/dev/null; then
    IN=/dev/tty
else
    IN=""; AUTO=1
fi
prompt() {  # prompt "question" -> $REPLY
    REPLY=""
    [ -n "$IN" ] || return 0
    ask "$1"
    read -r REPLY <"$IN" || REPLY=""
}

logo

# ---------------------------------------------------------- find the source
# Run from a clone (bash install.sh) or straight from curl: in the latter
# case there is no source tree next to us, so clone it into a temp dir.
SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "${BASH_SOURCE:-$0}")" 2>/dev/null && pwd || pwd)
if [ ! -f "$SCRIPT_DIR/run.py" ] || [ ! -d "$SCRIPT_DIR/termuxagent" ]; then
    if ! command -v git >/dev/null 2>&1; then
        if command -v pkg >/dev/null 2>&1; then
            say "installing git via pkg…"; pkg install -y git
        else
            warn "git not found — install git, or clone the repo and run: bash install.sh"
            exit 1
        fi
    fi
    TMP_SRC=$(mktemp -d 2>/dev/null || echo "${TMPDIR:-/tmp}/termuxagent-src.$$")
    say "fetching TermuxAgent from GitHub…"
    git clone --depth 1 -q "$REPO_URL" "$TMP_SRC/TermuxAgent0"
    SCRIPT_DIR="$TMP_SRC/TermuxAgent0"
    trap 'rm -rf "$TMP_SRC"' EXIT
fi
cd "$SCRIPT_DIR"

# ------------------------------------------------------------- python check
if command -v pkg >/dev/null 2>&1 && ! command -v python3 >/dev/null 2>&1; then
    say "Termux detected — installing python via pkg…"
    pkg install -y python || { pkg update -y && pkg install -y python; }
fi
if ! command -v python3 >/dev/null 2>&1; then
    warn "python3 not found. On Termux: pkg install -y python"
    exit 1
fi
PY=$(command -v python3)
if ! "$PY" -c "import sys; sys.exit(0 if sys.version_info >= (3, 8) else 1)"; then
    warn "python 3.8+ is required (found $("$PY" --version 2>&1)). On Termux: pkg upgrade python"
    exit 1
fi
say "using $("$PY" --version 2>&1) — no pip packages needed (pure stdlib)"
"$PY" -c "import urllib.request, json, subprocess, ssl; print('  stdlib check OK')" || {
    warn "python is missing its ssl module — on Termux run: pkg reinstall python openssl"
    exit 1
}

# ------------------------------------------------------------ copy app home
APP_HOME="$HOME/.termux-agent/app"
if [ "$SCRIPT_DIR" = "$APP_HOME" ]; then
    warn "already running from $APP_HOME — nothing to copy"
else
rm -rf "$APP_HOME"
mkdir -p "$APP_HOME"
if command -v tar >/dev/null 2>&1; then
    tar -cf - --exclude='.git' --exclude='__pycache__' --exclude='*.pyc' \
        termuxagent run.py | (cd "$APP_HOME" && tar -xf -)
else
    cp -r termuxagent run.py "$APP_HOME/"
    rm -rf "$APP_HOME/termuxagent/__pycache__"
fi
fi
chmod -R u+rwX "$APP_HOME" 2>/dev/null || true
say "app installed → $APP_HOME"

# big themed banner from the real app
( cd "$APP_HOME" && "$PY" -c "from termuxagent.theme import print_banner; print_banner('installing…')" ) 2>/dev/null || true

# ------------------------------------------------------------ launcher bins
write_launcher() {
    cat > "$1" <<LAUNCHER
#!/usr/bin/env bash
# TermuxAgent launcher (generated by install.sh)
export TERMUX_AGENT_APP="$APP_HOME"
PY="$PY"
command -v "\$PY" >/dev/null 2>&1 || PY=python3
exec "\$PY" "\$TERMUX_AGENT_APP/run.py" "\$@"
LAUNCHER
    chmod +x "$1"
}

INSTALLED_BIN=""
install_bins() {
    for BIN_DIR in "$@"; do
        [ -n "$BIN_DIR" ] || continue
        mkdir -p "$BIN_DIR" 2>/dev/null || true
        [ -d "$BIN_DIR" ] && [ -w "$BIN_DIR" ] || continue
        write_launcher "$BIN_DIR/agent"
        write_launcher "$BIN_DIR/Agent"   # capital-A: type 'Agent' and it opens
        say "commands installed → $BIN_DIR/agent  (and 'Agent')"
        INSTALLED_BIN="$BIN_DIR"
        return 0
    done
    return 1
}

TERMUX_PREFIX="${PREFIX:-}"
if [ -n "$TERMUX_PREFIX" ] && [ -d "$TERMUX_PREFIX/bin" ]; then
    install_bins "$TERMUX_PREFIX/bin" "$HOME/.local/bin" "$HOME/bin" || true
else
    install_bins "$HOME/.local/bin" "$HOME/bin" "/usr/local/bin" || true
fi
if [ -z "$INSTALLED_BIN" ]; then
    warn "could not write a launcher into PATH — run the agent with:"
    warn "  $PY $APP_HOME/run.py"
else
    case ":$PATH:" in
        *":$INSTALLED_BIN:"*) ;;
        *)
            warn "$INSTALLED_BIN is not in your PATH — adding it to your shell rc."
            LINE="export PATH=\"$INSTALLED_BIN:\$PATH\""
            for RC in "$HOME/.bashrc" "$HOME/.zshrc" "$HOME/.profile"; do
                [ -f "$RC" ] || [ "$RC" = "$HOME/.bashrc" ] || continue
                grep -qsF "$INSTALLED_BIN" "$RC" || printf '\n# TermuxAgent\n%s\n' "$LINE" >>"$RC"
            done
            warn "open a new terminal (or run: $LINE) before typing 'agent'."
            ;;
    esac
fi

printf "\n${GREEN}Install complete!${RESET}\n\n"
printf "  ${CYAN}agent${RESET}          open the AI agent   (or type ${CYAN}Agent${RESET})\n"
printf "  ${CYAN}agent setup${RESET}    change provider / key / model / theme\n"
printf "  ${CYAN}agent doctor${RESET}   diagnose problems\n"
printf "\n"

# ------------------------------------------------------------------- setup
if [ "$AUTO" = "1" ]; then
    printf "run ${CYAN}agent setup${RESET} to pick a provider and paste your API key.\n"
    exit 0
fi
prompt "run the setup wizard now? [Y/n] "
REPLY=${REPLY:-y}
if [ "$REPLY" = "y" ] || [ "$REPLY" = "Y" ]; then
    if [ -n "$IN" ] && [ "$IN" != /dev/stdin ]; then
        "$PY" "$APP_HOME/run.py" setup <"$IN"
    else
        "$PY" "$APP_HOME/run.py" setup
    fi
else
    printf "\nrun ${CYAN}agent setup${RESET} whenever you're ready.\n"
fi
