#!/usr/bin/env bash
# TermuxAgent installer — Termux (Android), Linux, macOS.
#
#   in Termux:   pkg install -y git python && git clone <repo> && cd TermuxAgent0 && bash install.sh
#   one-liner:   curl -fsSL https://raw.githubusercontent.com/sachintha8228888-cpu/TermuxAgent0/main/install.sh | bash
#
# What it does:
#   1. makes sure python3 exists (pkg install python on Termux)
#   2. copies the app to ~/.termux-agent/app (safe to delete the repo after)
#   3. installs the `agent` and `Agent` commands into PATH
#   4. runs the setup wizard (provider · API key · model · theme)
set -e

GREEN='\033[32m'; YELLOW='\033[33m'; CYAN='\033[36m'; MAGENTA='\033[35m'; RESET='\033[0m'
say()  { printf "${GREEN}[+]${RESET} %s\n" "$1"; }
ask()  { printf "${CYAN}[?]${RESET} %s" "$1"; }
warn() { printf "${YELLOW}[!]${RESET} %s\n" "$1"; }
logo() { printf "${MAGENTA}"
         printf '  ████████ ██ ██████   ████  ██   ██ ███    ██ ███████ ██████ \n'
         printf '  ─── TermuxAgent ── the AI that lives in your terminal ───\n'
         printf "${RESET}\n"; }

AUTO=0
[ "$1" = "--auto" ] || [ "$1" = "-y" ] && AUTO=1

SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
cd "$SCRIPT_DIR"

logo

# ------------------------------------------------------------- python check
if command -v pkg >/dev/null 2>&1 && ! command -v python3 >/dev/null 2>&1; then
    say "Termux detected — installing python via pkg…"
    pkg update -y
    pkg install -y python
fi
if ! command -v python3 >/dev/null 2>&1; then
    warn "python3 not found. On Termux: pkg install -y python"
    exit 1
fi
PY=python3
say "using $($PY --version 2>&1) — no pip packages needed (pure stdlib)"
$PY -c "import urllib.request, json, subprocess; print('  stdlib check OK')"

# ------------------------------------------------------------ copy app home
APP_HOME="$HOME/.termux-agent/app"
mkdir -p "$APP_HOME"
rm -rf "$APP_HOME"
mkdir -p "$APP_HOME"
if command -v tar >/dev/null 2>&1; then
    tar -cf - --exclude='.git' --exclude='__pycache__' --exclude='*.pyc' \
        termuxagent run.py | (cd "$APP_HOME" && tar -xf -)
else
    cp -r termuxagent run.py "$APP_HOME/"
    rm -rf "$APP_HOME/termuxagent/__pycache__"
fi
say "app installed → $APP_HOME"

# big themed banner from the real app
( cd "$APP_HOME" && $PY -c "from termuxagent.theme import print_banner; print_banner('installing…')" ) || logo

# ------------------------------------------------------------ launcher bins
write_launcher() {
    cat > "$1" <<LAUNCHER
#!/usr/bin/env bash
# TermuxAgent launcher (generated by install.sh)
export TERMUX_AGENT_APP="$APP_HOME"
exec $PY "\$TERMUX_AGENT_APP/run.py" "\$@"
LAUNCHER
    chmod +x "$1"
}

install_bins() {
    for BIN_DIR in "$@"; do
        [ -d "$BIN_DIR" ] && [ -w "$BIN_DIR" ] || continue
        write_launcher "$BIN_DIR/agent"
        write_launcher "$BIN_DIR/Agent"   # capital-A: type 'Agent' and it opens
        say "commands installed → $BIN_DIR/agent  (and 'Agent')"
        return 0
    done
    return 1
}

TERMUX_PREFIX="${PREFIX:-}"
if [ -n "$TERMUX_PREFIX" ] && [ -d "$TERMUX_PREFIX/bin" ]; then
    install_bins "$TERMUX_PREFIX/bin" "$HOME/.local/bin" "$HOME/bin" || true
else
    mkdir -p "$HOME/.local/bin"
    install_bins "$HOME/.local/bin" "$HOME/bin" "/usr/local/bin" || true
    case ":$PATH:" in
        *":$HOME/.local/bin:"*) ;;
        *) warn "~/.local/bin is not in your PATH. Add this line to ~/.bashrc:"
           warn '  export PATH="$HOME/.local/bin:$PATH"' ;;
    esac
fi

printf "\n${GREEN}Install complete!${RESET}\n\n"
printf "  ${CYAN}agent${RESET}          open the AI agent   (or type ${CYAN}Agent${RESET})\n"
printf "  ${CYAN}agent setup${RESET}    change provider / key / model / theme\n"
printf "  ${CYAN}agent doctor${RESET}   diagnose problems\n"
printf "\n"

# ------------------------------------------------------------------- setup
if [ "$AUTO" = "1" ]; then
    exit 0
fi
ask "run the setup wizard now? [Y/n] "
read -r REPLY
REPLY=${REPLY:-y}
if [ "$REPLY" = "y" ] || [ "$REPLY" = "Y" ]; then
    "$PY" "$APP_HOME/run.py" setup
else
    printf "\nrun ${CYAN}agent setup${RESET} whenever you're ready.\n"
fi
